/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#03b5d3",
        "on-secondary-fixed": "#001f26",
        "on-primary-fixed": "#002113",
        "on-error": "#690005",
        "on-primary-container": "#00422b",
        "surface": "#0f131c",
        "surface-container-low": "#181c24",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#31353e",
        "surface-tint": "#4edea3",
        "surface-container": "#1c2028",
        "inverse-on-surface": "#2c3039",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-fixed": "#acedff",
        "outline-variant": "#3c4a42",
        "inverse-primary": "#006c49",
        "tertiary": "#ffb95f",
        "tertiary-container": "#e29100",
        "on-surface": "#dfe2ee",
        "on-primary": "#003824",
        "surface-container-lowest": "#0a0e16",
        "on-secondary-container": "#00424e",
        "error": "#ffb4ab",
        "on-background": "#dfe2ee",
        "on-error-container": "#ffdad6",
        "primary-container": "#10b981",
        "outline": "#86948a",
        "on-primary-fixed-variant": "#005236",
        "on-secondary-fixed-variant": "#004e5c",
        "on-surface-variant": "#bbcabf",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffddb8",
        "background": "#0f131c",
        "surface-container-high": "#262a33",
        "on-tertiary-container": "#523200",
        "surface-variant": "#31353e",
        "primary-fixed-dim": "#4edea3",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-fixed-dim": "#4cd7f6",
        "secondary": "#4cd7f6",
        "primary-fixed": "#6ffbbe",
        "inverse-surface": "#dfe2ee",
        "surface-bright": "#353942",
        "primary": "#4edea3",
        "on-secondary": "#003640",
        "surface-dim": "#0f131c",
        "on-tertiary": "#472a00"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-base": "1rem",
        "space-2xl": "2rem",
        "space-xl": "1.5rem",
        "space-xs": "0.25rem",
        "space-2xs": "0.125rem",
        "gutter-mobile": "0.75rem",
        "space-md": "0.75rem",
        "panel-padding-compact": "0.875rem",
        "space-3xl": "3rem",
        "space-lg": "1.25rem",
        "space-sm": "0.5rem",
        "panel-padding-standard": "1.25rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        "mono-metric-md": ["JetBrains Mono", "monospace"],
        "label-badge": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "mono-metric-lg": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "mono-code-sm": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "mono-metric-md": ["16px", { lineHeight: "22px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "label-badge": ["10px", { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "500" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "mono-metric-lg": ["24px", { lineHeight: "30px", letterSpacing: "-0.03em", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "mono-code-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["15px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
