"""
decision_engine/reasoning_node.py
=================================
Azure AI Foundry reasoning node with structured output and resilient fallback.

Provides qualitative explanation, confidence assessment, and sanity checking
over causal uplift estimates using the gpt-4.1-mini deployment.
"""

from __future__ import annotations

import asyncio
import logging
import os
import time
from typing import Any, Literal, Optional
from urllib.parse import urlparse

from pydantic import BaseModel, Field
from decision_engine.state import RecoveryState
from decision_engine.structured_logger import emit_log

logger = logging.getLogger("decision_engine.reasoning_node")

# Pinned deployment name
FOUNDRY_MODEL_NAME = "gpt-4.1-mini"


def sanitize_fallback_reason_code(raw_reason: str) -> str:
    """
    Map raw fallback error/exception string to a safe, short, operational reason code.
    Never exposes raw exception strings or prompt contents.
    """
    text = (raw_reason or "").lower()
    if "timeout" in text or "deadline" in text:
        return "LLM_TIMEOUT"
    if "not in permitted" in text or "not in [" in text or "unpermitted" in text:
        return "LLM_UNPERMITTED_ACTION"
    if "validation" in text or "schema" in text or "pydantic" in text or "parse" in text or "rejected" in text:
        return "LLM_VALIDATION_ERROR"
    return "LLM_CALL_ERROR"


class LLMDecision(BaseModel):

    """
    Pydantic schema for structured reasoning output.
    Note: expected_incremental_value is strictly omitted from the prompt/schema
    and is joined downstream from the causal model.
    """

    decision: Literal["WAIT", "RETRY", "RETRY_NUDGE", "ESCALATE"]
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score in [0.0, 1.0]")
    reasoning: str = Field(description="Explanation and qualitative rationale for the chosen action")
    risk_level: Literal["low", "medium", "high"] = Field(description="Operational risk level")


def get_foundry_chat_model() -> Any:
    """
    Instantiate LangChain AzureAIOpenAIApiChatModel configured for the Azure AI Foundry deployment.

    Reads AZURE_OPENAI_API_KEY and AZURE_AI_PROJECT_ENDPOINT from environment.
    Uses Microsoft Foundry's OpenAI-compatible service endpoint (/openai/v1)
    derived from the project endpoint.
    """
    endpoint = os.getenv("AZURE_AI_PROJECT_ENDPOINT", "").strip()
    api_key = os.getenv("AZURE_OPENAI_API_KEY", "").strip()

    if not endpoint or not api_key:
        raise ValueError(
            "Azure Foundry credentials missing: AZURE_AI_PROJECT_ENDPOINT and "
            "AZURE_OPENAI_API_KEY must be set."
        )

    parsed = urlparse(endpoint)
    # Microsoft Foundry OpenAI-compatible service endpoint (/openai/v1)
    service_endpoint = f"{parsed.scheme}://{parsed.netloc}/openai/v1"

    try:
        from langchain_azure_ai.chat_models import AzureAIOpenAIApiChatModel

        return AzureAIOpenAIApiChatModel(
            endpoint=service_endpoint,
            credential=api_key,
            model=FOUNDRY_MODEL_NAME,
            temperature=0,
        )
    except ImportError:
        from langchain_openai import ChatOpenAI

        return ChatOpenAI(
            base_url=service_endpoint,
            api_key=api_key,
            model=FOUNDRY_MODEL_NAME,
            temperature=0,
        )



def _build_prompt(
    observable_features: dict[str, Any],
    arm_probabilities: dict[str, float],
    arm_net_values: dict[str, float],
    permitted_actions: list[str],
) -> str:
    """Construct the system/user instruction prompt for the reasoning node."""
    return f"""You are the Recovery Intelligence Reasoning Engine.
Your role is qualitative explanation and sanity-checking of causal recommendations.

CRITICAL CONSTRAINTS:
1. The supplied arm probabilities and net values were generated by a validated causal ML model (T-Learner).
2. You must NOT invent, guess, or recalculate probabilities.
3. You must NOT invent, guess, or alter net values.
4. You MUST choose an action strictly from the list of permitted actions: {permitted_actions}.
5. Any proposed action outside {permitted_actions} will be rejected immediately.

Observable Features:
{observable_features}

Causal Arm Recovery Probabilities:
{arm_probabilities}

Net Expected Values (INR, after intervention costs):
{arm_net_values}

Permitted Actions:
{permitted_actions}

Provide your structured decision, confidence, reasoning, and risk level.
"""


def _execute_fallback(
    state: RecoveryState,
    permitted_actions: list[str],
    arm_net_values: dict[str, float],
    reason: str,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Execute deterministic fallback by taking argmax over permitted arm net values."""
    # Ensure we only consider permitted actions
    valid_arms = [a for a in permitted_actions if a in arm_net_values]
    if not valid_arms:
        fallback_action = "WAIT"
    else:
        fallback_action = max(valid_arms, key=lambda a: arm_net_values.get(a, float("-inf")))

    expected_val = float(arm_net_values.get(fallback_action, 0.0))

    fallback_decision = {
        "decision": fallback_action,
        "confidence": 1.0,
        "reasoning": "LLM fallback — using argmax directly",
        "risk_level": "medium",
        "expected_incremental_value": expected_val,
        "decision_source": "fallback_no_llm",
    }

    # Emit structured event on deterministic fallback with sanitized reason code [Day 7G]
    reason_code = sanitize_fallback_reason_code(reason)
    emit_log(
        logger,
        logging.WARNING,
        "llm_fallback_triggered",
        request_id or "",
        reason_code=reason_code,
        fallback_action=fallback_action,
    )

    return {
        "llm_decision": fallback_decision,
        "final_action": fallback_action,
        "audit_trail": [
            {
                "node": "reasoning_node",
                "status": "fallback",
                "reason": reason,
                "fallback_action": fallback_action,
                "decision_source": "fallback_no_llm",
                "expected_incremental_value": expected_val,
            }
        ],
    }


def reasoning_node(
    state: RecoveryState,
    llm: Any = None,
) -> dict[str, Any]:
    """
    Execute qualitative reasoning using Azure AI Foundry with retry and deterministic fallback.

    Parameters
    ----------
    state : RecoveryState
        Current LangGraph workflow state.
    llm : Any, optional
        Injected LLM instance for testing without external network calls.

    Returns
    -------
    dict[str, Any]
        Partial state dictionary update.
    """
    # If prior error, skip reasoning node
    if state.get("error"):
        return {
            "final_action": "WAIT",
            "audit_trail": [
                {
                    "node": "reasoning_node",
                    "status": "skipped",
                    "reason": f"Skipped due to prior error: {state.get('error')}",
                }
            ],
        }

    observable_features = state.get("observable_features", {})
    arm_probabilities = state.get("arm_probabilities", {})
    arm_net_values = state.get("arm_net_values", {})
    permitted_actions = state.get("permitted_actions", ["WAIT"])

    if not permitted_actions:
        permitted_actions = ["WAIT"]

    # Initialize model
    active_llm = llm if llm is not None else get_foundry_chat_model()
    structured_llm = active_llm.with_structured_output(LLMDecision)

    base_prompt = _build_prompt(
        observable_features=observable_features,
        arm_probabilities=arm_probabilities,
        arm_net_values=arm_net_values,
        permitted_actions=permitted_actions,
    )

    # ── Attempt 1 ─────────────────────────────────────────────────────────────
    parsed_output = None
    attempt1_error = None

    try:
        res = structured_llm.invoke(base_prompt)
        # Verify action is in permitted_actions
        if res.decision not in permitted_actions:
            attempt1_error = (
                f"Proposed decision {res.decision!r} is not in permitted_actions {permitted_actions}"
            )
        else:
            parsed_output = res
    except Exception as exc:
        attempt1_error = f"Attempt 1 failed: {exc}"

    if parsed_output is not None:
        chosen_action = parsed_output.decision
        expected_val = float(arm_net_values.get(chosen_action, 0.0))

        decision_data = {
            "decision": chosen_action,
            "confidence": float(parsed_output.confidence),
            "reasoning": parsed_output.reasoning,
            "risk_level": parsed_output.risk_level,
            "expected_incremental_value": expected_val,
            "decision_source": "llm",
        }

        return {
            "llm_decision": decision_data,
            "final_action": chosen_action,
            "audit_trail": [
                {
                    "node": "reasoning_node",
                    "status": "success",
                    "attempt": 1,
                    "decision": chosen_action,
                    "decision_source": "llm",
                    "expected_incremental_value": expected_val,
                }
            ],
        }

    # ── Attempt 2 (Retry with explicit correction message) ────────────────────
    attempt2_error = None
    correction_prompt = (
        f"{base_prompt}\n\n"
        f"CORRECTION REQUIRED: Your previous output was rejected with error: {attempt1_error}.\n"
        f"You MUST select an action strictly from: {permitted_actions}. Do not deviate."
    )

    try:
        res_retry = structured_llm.invoke(correction_prompt)
        if res_retry.decision not in permitted_actions:
            attempt2_error = (
                f"Attempt 2 rejected: decision {res_retry.decision!r} not in {permitted_actions}"
            )
        else:
            chosen_action = res_retry.decision
            expected_val = float(arm_net_values.get(chosen_action, 0.0))

            decision_data = {
                "decision": chosen_action,
                "confidence": float(res_retry.confidence),
                "reasoning": res_retry.reasoning,
                "risk_level": res_retry.risk_level,
                "expected_incremental_value": expected_val,
                "decision_source": "llm_retry_success",
            }

            return {
                "llm_decision": decision_data,
                "final_action": chosen_action,
                "audit_trail": [
                    {
                        "node": "reasoning_node",
                        "status": "success",
                        "attempt": 2,
                        "decision": chosen_action,
                        "decision_source": "llm_retry_success",
                        "expected_incremental_value": expected_val,
                    }
                ],
            }
    except Exception as exc:
        attempt2_error = f"Attempt 2 failed: {exc}"

    # ── Fallback (Both attempts failed) ───────────────────────────────────────
    combined_reason = f"Attempt 1: {attempt1_error} | Attempt 2: {attempt2_error}"
    return _execute_fallback(
        state=state,
        permitted_actions=permitted_actions,
        arm_net_values=arm_net_values,
        reason=combined_reason,
    )


async def async_reasoning_node(
    state: RecoveryState,
    llm: Any = None,
    deadline: Optional[float] = None,
    semaphore: Optional[asyncio.Semaphore] = None,
    config: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    """
    Asynchronous reasoning node using Azure AI Foundry with native async invocation,
    shared request deadline bounding, and semaphore concurrency control.

    Parameters
    ----------
    state : RecoveryState
        Current LangGraph workflow state.
    llm : Any, optional
        Injected LLM instance for testing without external network calls.
    deadline : float, optional
        Monotonic deadline timestamp (time.monotonic()) for the request.
    semaphore : asyncio.Semaphore, optional
        Concurrency semaphore for LLM calls.
    config : dict, optional
        LangGraph RunnableConfig containing configurable runtime parameters.

    Returns
    -------
    dict[str, Any]
        Partial state dictionary update.
    """
    configurable = (config.get("configurable", {}) if config else {})
    effective_deadline = deadline if deadline is not None else configurable.get("llm_deadline")
    effective_semaphore = semaphore if semaphore is not None else configurable.get("llm_semaphore")
    request_id = configurable.get("request_id")

    def _attach_request_id(update_dict: dict[str, Any]) -> dict[str, Any]:
        if request_id and "audit_trail" in update_dict:
            for ev in update_dict["audit_trail"]:
                ev["request_id"] = request_id
        return update_dict

    if state.get("error"):
        return _attach_request_id({
            "final_action": "WAIT",
            "audit_trail": [
                {
                    "node": "reasoning_node",
                    "status": "skipped",
                    "reason": f"Skipped due to prior error: {state.get('error')}",
                }
            ],
        })

    observable_features = state.get("observable_features", {})
    arm_probabilities = state.get("arm_probabilities", {})
    arm_net_values = state.get("arm_net_values", {})
    permitted_actions = state.get("permitted_actions", ["WAIT"])

    if not permitted_actions:
        permitted_actions = ["WAIT"]

    active_llm = llm if llm is not None else get_foundry_chat_model()
    structured_llm = active_llm.with_structured_output(LLMDecision)

    base_prompt = _build_prompt(
        observable_features=observable_features,
        arm_probabilities=arm_probabilities,
        arm_net_values=arm_net_values,
        permitted_actions=permitted_actions,
    )

    async def _call_llm_async(prompt_str: str) -> Any:
        # 1. Check remaining deadline before semaphore acquisition
        if effective_deadline is not None:
            remaining = effective_deadline - time.monotonic()
            if remaining <= 0:
                raise asyncio.TimeoutError("Deadline exceeded before acquiring LLM semaphore slot")
        else:
            remaining = None

        # 2. Acquire semaphore if provided
        sem_acquired = False
        sem_wait_start = time.monotonic()
        if effective_semaphore is not None:
            if remaining is not None:
                await asyncio.wait_for(effective_semaphore.acquire(), timeout=remaining)
            else:
                await effective_semaphore.acquire()
            sem_acquired = True
            sem_wait_ms = round((time.monotonic() - sem_wait_start) * 1000, 2)
            emit_log(
                logger,
                logging.INFO,
                "semaphore_wait",
                request_id or "",
                wait_ms=sem_wait_ms,
            )


        try:
            # 3. Re-check remaining deadline after acquiring semaphore
            if effective_deadline is not None:
                call_remaining = effective_deadline - time.monotonic()
                if call_remaining <= 0:
                    raise asyncio.TimeoutError("Deadline exceeded while waiting for LLM semaphore slot")
            else:
                call_remaining = None

            # 4. Invoke LLM asynchronously using native ainvoke (or to_thread fallback for sync test mocks)
            t_llm_start = time.monotonic()
            if hasattr(structured_llm, "ainvoke"):
                coro = structured_llm.ainvoke(prompt_str)
            else:
                coro = asyncio.to_thread(structured_llm.invoke, prompt_str)

            if call_remaining is not None:
                call_res = await asyncio.wait_for(coro, timeout=call_remaining)
            else:
                call_res = await coro
            call_ms = round((time.monotonic() - t_llm_start) * 1000, 2)
            return call_res, call_ms
        finally:
            if sem_acquired:
                effective_semaphore.release()

    # ── Attempt 1 ─────────────────────────────────────────────────────────────
    parsed_output = None
    attempt1_error = None
    total_llm_duration_ms = 0.0

    try:
        res, call_ms = await _call_llm_async(base_prompt)
        total_llm_duration_ms += call_ms
        if res.decision not in permitted_actions:
            attempt1_error = (
                f"Proposed decision {res.decision!r} is not in permitted_actions {permitted_actions}"
            )
        else:
            parsed_output = res
    except Exception as exc:
        attempt1_error = f"Attempt 1 failed: {exc}"

    if parsed_output is not None:
        chosen_action = parsed_output.decision
        expected_val = float(arm_net_values.get(chosen_action, 0.0))

        decision_data = {
            "decision": chosen_action,
            "confidence": float(parsed_output.confidence),
            "reasoning": parsed_output.reasoning,
            "risk_level": parsed_output.risk_level,
            "expected_incremental_value": expected_val,
            "decision_source": "llm",
            "llm_duration_ms": total_llm_duration_ms,
        }

        return _attach_request_id({
            "llm_decision": decision_data,
            "llm_duration_ms": total_llm_duration_ms,
            "final_action": chosen_action,
            "audit_trail": [
                {
                    "node": "reasoning_node",
                    "status": "success",
                    "attempt": 1,
                    "decision": chosen_action,
                    "decision_source": "llm",
                    "expected_incremental_value": expected_val,
                    "llm_duration_ms": total_llm_duration_ms,
                }
            ],
        })

    # ── Attempt 2 (Retry with explicit correction message) ────────────────────
    attempt2_error = None
    correction_prompt = (
        f"{base_prompt}\n\n"
        f"CORRECTION REQUIRED: Your previous output was rejected with error: {attempt1_error}.\n"
        f"You MUST select an action strictly from: {permitted_actions}. Do not deviate."
    )

    try:
        res_retry, retry_call_ms = await _call_llm_async(correction_prompt)
        total_llm_duration_ms += retry_call_ms
        if res_retry.decision not in permitted_actions:
            attempt2_error = (
                f"Attempt 2 rejected: decision {res_retry.decision!r} not in {permitted_actions}"
            )
        else:
            chosen_action = res_retry.decision
            expected_val = float(arm_net_values.get(chosen_action, 0.0))

            decision_data = {
                "decision": chosen_action,
                "confidence": float(res_retry.confidence),
                "reasoning": res_retry.reasoning,
                "risk_level": res_retry.risk_level,
                "expected_incremental_value": expected_val,
                "decision_source": "llm_retry_success",
                "llm_duration_ms": total_llm_duration_ms,
            }

            return _attach_request_id({
                "llm_decision": decision_data,
                "llm_duration_ms": total_llm_duration_ms,
                "final_action": chosen_action,
                "audit_trail": [
                    {
                        "node": "reasoning_node",
                        "status": "success",
                        "attempt": 2,
                        "decision": chosen_action,
                        "decision_source": "llm_retry_success",
                        "expected_incremental_value": expected_val,
                        "llm_duration_ms": total_llm_duration_ms,
                    }
                ],
            })
    except Exception as exc:
        attempt2_error = f"Attempt 2 failed: {exc}"

    # ── Fallback (Both attempts failed) ───────────────────────────────────────
    combined_reason = f"Attempt 1: {attempt1_error} | Attempt 2: {attempt2_error}"
    return _attach_request_id(
        _execute_fallback(
            state=state,
            permitted_actions=permitted_actions,
            arm_net_values=arm_net_values,
            reason=combined_reason,
            request_id=request_id,
        )
    )


